#!/bin/bash
trap "./myscript_5_2" SIGINT
trap "echo GOODBYE" EXIT
count=1
while [ $count -le 10 ]
do
echo "this is #$count string"
sleep 1
count=$(( $count + 1 ))
done
trap -- SIGINT
echo " modify trapped"
count=1
while [ $count -le 5 ]
do 
echo " new loop #$count"
sleep 5
count=$(( $count + 1 ))
done
