#!/bin/bash
file="myscript1"
file2="myscript2"
if [ -x $file ]
then
echo "this is xmod file"
fi
if [ -s $file ]
then
echo "this is file"
fi
if [ file -nt file2 ]
then
echo "$file newtter $file2"
else
echo "$file older $file2"
fi
