#!/bin/bash
HOME=$(pwd)
file="myscript"
found=$(ls $HOME)
echo "ls HOME: $found"
echo "this work director: $HOME"
echo "file: $file"
echo "found directory: $found"
echo "pwd: $(pwd)"
if grep $file $found
then
echo "GOOD"
fi 
